[project]
name = "sthlm-puls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LisaYllander92", email = "Lisaylander92@gmail.com" },
    { name = "rickardgarnau-byte", email = "rickardgarnau@email.com" }
]
requires-python = ">=3.13"
dependencies = [
    "css>=0.1",
    "duckdb>=1.5.2",
    "matplotlib>=3.10.9",
    "pandas>=3.0.2",
    "pydeck>=0.9.2",
    "streamlit>=1.57.0",
]

[project.scripts]
sthlm-puls = "sthlm_puls:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

